services:
  mssql:
    image: chriseaton/adventureworks:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    # logging:
    #   driver: none

  wait:
    image: wait-for-mssql:latest
    command: --max 10 --delay 10 --verbose true --database AdventureWorks

    depends_on:
      - mssql
    build:
      context: src
      dockerfile: Dockerfile
